Producto.create!(id: 1, nombre: 'Aceite Natura Girasol x 1,1 Lts', clasificacion: 'Almacén > Aceites', precio: 325.0, imagen_url: '00001.jpg')
Producto.create!(id: 5, nombre: 'Aceite Vicentin Girasol 900cc', clasificacion: 'Almacén > Aceites', precio: 210.0, imagen_url: '00005.jpg')
Producto.create!(id: 7, nombre: 'Acondicionador Suave Aloe Vera y Pepino 930ml', clasificacion: 'Limpieza > Shampoo', precio: 120.0, imagen_url: '00007.jpg')
Producto.create!(id: 9, nombre: 'Aji Alicante Triturado 25gr', clasificacion: 'Condimentos > Condimentos', precio: 32.5, imagen_url: '00009.jpg')
Producto.create!(id: 14, nombre: 'Arroz Gallo Oro 1kg', clasificacion: 'Almacén > Arroz', precio: 136.0, imagen_url: '00014.jpg')
Producto.create!(id: 15, nombre: 'Arroz Gallo Oro Amarillo 500gr', clasificacion: 'Almacén > Arroz', precio: 84.0, imagen_url: '00015.jpg')
Producto.create!(id: 16, nombre: 'Arroz Luchador 4/0 500gr', clasificacion: 'Almacén > Arroz', precio: 45.0, imagen_url: '00016.jpg')
Producto.create!(id: 19, nombre: 'Arvejas Arcor Secas 300gr', clasificacion: 'Almacén > Enlatados', precio: 64.0, imagen_url: '00019.jpg')
Producto.create!(id: 20, nombre: 'Arvejas Inalpa 350gr', clasificacion: 'Almacén > Enlatados', precio: 32.5, imagen_url: '00020.jpg')
Producto.create!(id: 23, nombre: 'Azucar 1kg', clasificacion: 'Almacén > Azúcar', precio: 58.0, imagen_url: '00023.jpg')
Producto.create!(id: 25, nombre: 'Azucar Villa Rica Impalpable 250gr', clasificacion: 'Condimentos > Condimentos', precio: 44.0, imagen_url: '00025.jpg')
Producto.create!(id: 26, nombre: 'Bicarbonato Villa Rica 20gr', clasificacion: 'Condimentos > Condimentos', precio: 7.0, imagen_url: '00026.jpg')
Producto.create!(id: 29, nombre: 'Bizcochuelo Godet Vainilla 480gr', clasificacion: 'Almacén > Postres', precio: 130.0, imagen_url: '00029.jpg')
Producto.create!(id: 30, nombre: 'Bondiola Goggi Feteada x 100gr', clasificacion: 'Fiambreria > Bondiola', precio: 110.0, imagen_url: '00030.jpg')
Producto.create!(id: 31, nombre: 'Bondiola Lario Feteada x 100gr', clasificacion: 'Fiambreria > Bondiola', precio: 170.0, imagen_url: '00031.jpg')
Producto.create!(id: 34, nombre: 'Burgol Jose Lopez 500gr', clasificacion: 'Almacén > Legumbres', precio: 92.0, imagen_url: '00034.jpg')
Producto.create!(id: 35, nombre: 'Burgol La Espanola 500gr', clasificacion: 'Almacén > Legumbres', precio: 87.0, imagen_url: '00035.jpg')
Producto.create!(id: 37, nombre: 'Caballa Marbella Al Ac/nat 425gr', clasificacion: 'Almacén > Enlatados', precio: 218.0, imagen_url: '00037.jpg')
Producto.create!(id: 39, nombre: 'Cacao Chocolino Plus Fort 180gr', clasificacion: 'Desayuno > Cacao', precio: 80.0, imagen_url: '00039.jpg')
Producto.create!(id: 42, nombre: 'Cafe Arlistan 100gr', clasificacion: 'Almacén > Café', precio: 220.0, imagen_url: '00042.jpg')
Producto.create!(id: 50, nombre: 'Cafe La Morenita Saq 20* 5gr', clasificacion: 'Almacén > Café', precio: 161.0, imagen_url: '00050.jpg')
Producto.create!(id: 52, nombre: 'Cafe La Virginia Clasico Instantaneo 100gr', clasificacion: 'Almacén > Café', precio: 218.0, imagen_url: '00052.jpg')
Producto.create!(id: 53, nombre: 'Cafe La Virginia En Sobres ( 5gr .)', clasificacion: 'Almacén > Café', precio: 172.0, imagen_url: '00053.jpg')
Producto.create!(id: 55, nombre: 'Cafe La Virginia Instantaneo Cortado 125gr', clasificacion: 'Almacén > Café', precio: 149.0, imagen_url: '00055.jpg')
Producto.create!(id: 56, nombre: 'Cafe La Virginia Instantaneo Latte 125gr', clasificacion: 'Almacén > Café', precio: 149.0, imagen_url: '00056.jpg')
Producto.create!(id: 58, nombre: 'Cafe La Virginia Suave 170gr . Vidrio', clasificacion: 'Almacén > Café', precio: 325.0, imagen_url: '00058.jpg')
Producto.create!(id: 61, nombre: 'Camellito Ropa Fina 450ml Doypack', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 98.55, imagen_url: '00061.jpg')
Producto.create!(id: 62, nombre: 'Casancrem Descremado 290gr', clasificacion: 'Frescos y Congelados > Untables', precio: 230.0, imagen_url: '00062.jpg')
Producto.create!(id: 63, nombre: 'Casancrem Entero 290gr', clasificacion: 'Frescos y Congelados > Untables', precio: 230.0, imagen_url: '00063.jpg')
Producto.create!(id: 67, nombre: 'Chimichurri Alicante x 25gr', clasificacion: 'Condimentos > Condimentos', precio: 51.5, imagen_url: '00067.jpg')
Producto.create!(id: 69, nombre: 'Chisitos Facu 400gr', clasificacion: 'Snacks > Chisitos', precio: 105.0, imagen_url: '00069.jpg')
Producto.create!(id: 74, nombre: 'Cif Crema Original x 375gr', clasificacion: 'Limpieza > Varios', precio: 80.0, imagen_url: '00074.jpg')
Producto.create!(id: 76, nombre: 'Comino Alicante 25gr', clasificacion: 'Condimentos > Condimentos', precio: 52.5, imagen_url: '00076.jpg')
Producto.create!(id: 77, nombre: 'Comino Villa Rica 25gr', clasificacion: 'Condimentos > Condimentos', precio: 28.0, imagen_url: '00077.jpg')
Producto.create!(id: 78, nombre: 'Cond Villa Rica Arroz 25gr', clasificacion: 'Condimentos > Condimentos', precio: 20.5, imagen_url: '00078.jpg')
Producto.create!(id: 80, nombre: 'Condimento Para Arroz Alicante 25gr', clasificacion: 'Condimentos > Condimentos', precio: 39.0, imagen_url: '00080.jpg')
Producto.create!(id: 83, nombre: 'Dentifrico Colgate 70gr', clasificacion: 'Limpieza > Dentifrico', precio: 105.0, imagen_url: '00083.jpg')
Producto.create!(id: 84, nombre: 'Dentifrico Kolynos 180gr', clasificacion: 'Limpieza > Dentifrico', precio: 225.0, imagen_url: '00084.jpg')
Producto.create!(id: 85, nombre: 'Dentifrico Odol 180gr', clasificacion: 'Limpieza > Dentifrico', precio: 210.0, imagen_url: '00085.jpg')
Producto.create!(id: 86, nombre: 'Dentifrico Odol 70gr', clasificacion: 'Limpieza > Dentifrico', precio: 90.0, imagen_url: '00086.jpg')
Producto.create!(id: 91, nombre: 'Detergente Camellito Ropa Fina 120ml', clasificacion: 'Limpieza > Detergente', precio: 39.06, imagen_url: '00091.jpg')
Producto.create!(id: 93, nombre: 'Dulce De Batata Dulcor Cajon 5kg', clasificacion: 'Almacén > Otros', precio: 535.0, imagen_url: '00093.jpg')
Producto.create!(id: 94, nombre: 'Dulce De Batata La Riojanita Cajon 5kg Ch', clasificacion: 'Almacén > Otros', precio: 505.0, imagen_url: '00094.jpg')
Producto.create!(id: 95, nombre: 'Dulce De Batata Riojanita Cajon 5kg Vainilla', clasificacion: 'Almacén > Otros', precio: 490.0, imagen_url: '00095.jpg')
Producto.create!(id: 96, nombre: 'Dulce De Batata Riojanita Vainilla Lata x 5kg', clasificacion: 'Almacén > Otros', precio: 742.5, imagen_url: '00096.jpg')
Producto.create!(id: 97, nombre: 'Dulce De Leche Cerros Tucumanos 1kg', clasificacion: 'Lacteos > Dulce de Leche', precio: 193.5, imagen_url: '00097.jpg')
Producto.create!(id: 101, nombre: 'Durazno En Lata Precursor x 820gr', clasificacion: 'Almacén > Enlatados', precio: 145.5, imagen_url: '00101.jpg')
Producto.create!(id: 103, nombre: 'Edulcorante Si Diet 200cc', clasificacion: 'Desayuno > Edulcorantes', precio: 79.8, imagen_url: '00103.jpg')
Producto.create!(id: 106, nombre: 'Escobillon Fede Sin Cabo', clasificacion: 'Limpieza > Varios', precio: 155.0, imagen_url: '00106.jpg')
Producto.create!(id: 109, nombre: 'Extracto Tomate Otito 150gr', clasificacion: 'Almacén > Salsas', precio: 60.83, imagen_url: '00109.jpg')
Producto.create!(id: 110, nombre: 'Fecula Glutal 5kg', clasificacion: 'Almacén > Varios', precio: 342.0, imagen_url: '00110.jpg')
Producto.create!(id: 111, nombre: 'Fernet Branca 750cc', clasificacion: 'Bebidas > Cervezas y Fernet', precio: 560.0, imagen_url: '00111.jpg')
Producto.create!(id: 112, nombre: 'Fiambre Cocido Goggi Etiqueta Azul x 100gr', clasificacion: 'Fiambreria > Fiambre cocido', precio: 18.0, imagen_url: '00112.jpg')
Producto.create!(id: 114, nombre: 'Fideos Chicago Guiseros 500gr', clasificacion: 'Almacén > Fideos', precio: 48.0, imagen_url: '00114.jpg')
Producto.create!(id: 117, nombre: 'Fideos La Providencia Spaguetti 500gr', clasificacion: 'Almacén > Fideos', precio: 47.5, imagen_url: '00117.jpg')
Producto.create!(id: 119, nombre: 'Fideos Parradin 500gr', clasificacion: 'Almacén > Fideos', precio: 45.0, imagen_url: '00119.jpg')
Producto.create!(id: 120, nombre: 'Fideos Rivoli Guisero/sopero 500gr', clasificacion: 'Almacén > Fideos', precio: 60.0, imagen_url: '00120.jpg')
Producto.create!(id: 124, nombre: 'Flan Godet Vainilla 30gr', clasificacion: 'Almacén > Postres', precio: 37.5, imagen_url: '00124.jpg')
Producto.create!(id: 126, nombre: 'Galletas Bagley Salvado 3 x 214gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 185.0, imagen_url: '00126.jpg')
Producto.create!(id: 129, nombre: 'Galletas Chocolinas 100gr . Bagley', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 54.9, imagen_url: '00129.jpg')
Producto.create!(id: 131, nombre: 'Galletas De Arroz All Rice Dulces x 100gr', clasificacion: 'Almacén > Varios', precio: 71.0, imagen_url: '00131.jpg')
Producto.create!(id: 133, nombre: 'Galletas De Arroz All Rice Naranja x 100gr', clasificacion: 'Almacén > Varios', precio: 71.0, imagen_url: '00133.jpg')
Producto.create!(id: 135, nombre: 'Galletas Diversion Surt x 400 Arcor', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 105.0, imagen_url: '00135.jpg')
Producto.create!(id: 137, nombre: 'Galletas Formis 108gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 58.9, imagen_url: '00137.jpg')
Producto.create!(id: 139, nombre: 'Galletas Mana 145gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 57.5, imagen_url: '00139.jpg')
Producto.create!(id: 140, nombre: 'Galletas Mana Rell 165gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 69.5, imagen_url: '00140.jpg')
Producto.create!(id: 141, nombre: 'Galletas Mauri Sin Sal 400gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 112.0, imagen_url: '00141.jpg')
Producto.create!(id: 142, nombre: 'Galletas Merengada 93gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 59.5, imagen_url: '00142.jpg')
Producto.create!(id: 144, nombre: 'Galletas Porte?itas 125gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 62.0, imagen_url: '00144.jpg')
Producto.create!(id: 146, nombre: 'Galletas Surtido Bagley 400gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 129.5, imagen_url: '00146.jpg')
Producto.create!(id: 148, nombre: 'Grasa Vacuna Kamote x 500gr', clasificacion: 'Almacén > Otros', precio: 50.0, imagen_url: '00148.jpg')
Producto.create!(id: 149, nombre: 'Hamburguesa Paladini 2un', clasificacion: 'Frescos y Congelados > Hamburguesas', precio: 150.0, imagen_url: '00149.jpg')
Producto.create!(id: 150, nombre: 'Hamburguesa Swift Doble (2 Uds.)', clasificacion: 'Frescos y Congelados > Hamburguesas', precio: 56.75, imagen_url: '00150.jpg')
Producto.create!(id: 152, nombre: 'Hamburguesas Iacono 2 x 69gr', clasificacion: 'Frescos y Congelados > Hamburguesas', precio: 43.5, imagen_url: '00152.jpg')
Producto.create!(id: 157, nombre: 'Harina Reina Ana 000 x 1kg', clasificacion: 'Almacén > Harinas', precio: 36.0, imagen_url: '00157.jpg')
Producto.create!(id: 159, nombre: 'Jabon Ace Liquido Doypack x 800ml', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 130.0, imagen_url: '00159.jpg')
Producto.create!(id: 160, nombre: 'Jabon Ala Liquido x 400ml', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 55.5, imagen_url: '00160.jpg')
Producto.create!(id: 161, nombre: 'Jabon Ala Matic 400gr', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 93.8, imagen_url: '00161.jpg')
Producto.create!(id: 162, nombre: 'Jabon Ala Matic 800gr', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 169.0, imagen_url: '00162.jpg')
Producto.create!(id: 163, nombre: 'Jabon Ala Pan 200gr', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 48.0, imagen_url: '00163.jpg')
Producto.create!(id: 165, nombre: 'Jabon Ariel Liquido Doypack x 400ml', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 79.0, imagen_url: '00165.jpg')
Producto.create!(id: 169, nombre: 'Jabon Zorro Plus Matic 400gr', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 53.0, imagen_url: '00169.jpg')
Producto.create!(id: 170, nombre: 'Jamon Cocido Goggi Con Cuero Feteado x 100gr', clasificacion: 'Fiambreria > Jamón', precio: 60.0, imagen_url: '00170.jpg')
Producto.create!(id: 171, nombre: 'Jamon Cocido Goggi Feteado x 100gr', clasificacion: 'Fiambreria > Jamón', precio: 58.0, imagen_url: '00171.jpg')
Producto.create!(id: 172, nombre: 'Jamon Cocido Lario Feteado x 100gr', clasificacion: 'Fiambreria > Jamón', precio: 85.0, imagen_url: '00172.jpg')
Producto.create!(id: 174, nombre: 'Jamon Crudo Goggi Feteado x 100gr', clasificacion: 'Fiambreria > Jamon Crudo', precio: 100.0, imagen_url: '00174.jpg')
Producto.create!(id: 175, nombre: 'Jugo Ades Manzana 1lt', clasificacion: 'Bebidas > Jugos', precio: 115.0, imagen_url: '00175.jpg')
Producto.create!(id: 177, nombre: 'Jugo Arcor 25gr Sobres', clasificacion: 'Bebidas > Jugos', precio: 18.0, imagen_url: '00177.jpg')
Producto.create!(id: 178, nombre: 'Jugo Baggio Durazno 200cc', clasificacion: 'Bebidas > Jugos', precio: 24.0, imagen_url: '00178.jpg')
Producto.create!(id: 179, nombre: 'Jugo Baggio Fresh Manzana Deliciosa 1,1lt', clasificacion: 'Bebidas > Jugos', precio: 62.0, imagen_url: '00179.jpg')
Producto.create!(id: 180, nombre: 'Jugo Baggio Multifruta 125cc', clasificacion: 'Bebidas > Jugos', precio: 16.5, imagen_url: '00180.jpg')
Producto.create!(id: 181, nombre: 'Jugo Bc Sobres 1lt', clasificacion: 'Bebidas > Jugos', precio: 20.0, imagen_url: '00181.jpg')
Producto.create!(id: 182, nombre: 'Jugo Dodi 25gr Rinde 2lt', clasificacion: 'Bebidas > Jugos', precio: 14.0, imagen_url: '00182.jpg')
Producto.create!(id: 183, nombre: 'Ketchup Danica 220gr', clasificacion: 'Aderezos > Ketchup', precio: 63.5, imagen_url: '00183.jpg')
Producto.create!(id: 185, nombre: 'Laurel En Hojas Alicante 10gr', clasificacion: 'Condimentos > Condimentos', precio: 68.0, imagen_url: '00185.jpg')
Producto.create!(id: 189, nombre: 'Leche Condensada Nestle 395gr', clasificacion: 'Lacteos > Leche Condensada', precio: 199.0, imagen_url: '00189.jpg')
Producto.create!(id: 191, nombre: 'Leche En Polvo Descremada Lheritier 350gr', clasificacion: 'Lacteos > Leche en Polvo', precio: 199.01, imagen_url: '00191.jpg')
Producto.create!(id: 195, nombre: 'Leche Nido Fort Tapa Amarilla 800gr', clasificacion: 'Lacteos > Leche en Polvo', precio: 430.0, imagen_url: '00195.jpg')
Producto.create!(id: 196, nombre: 'Lenteja Jose Lopez 500gr', clasificacion: 'Almacén > Legumbres', precio: 130.0, imagen_url: '00196.jpg')
Producto.create!(id: 197, nombre: 'Levadura Duquesa 500gr', clasificacion: 'Frescos y Congelados > Levaduras', precio: 130.0, imagen_url: '00197.jpg')
Producto.create!(id: 201, nombre: 'Maiz Blanco Jose Lopez 500gr', clasificacion: 'Almacén > Legumbres', precio: 63.5, imagen_url: '00201.jpg')
Producto.create!(id: 202, nombre: 'Maiz Blanco La Espanola 500gr', clasificacion: 'Almacén > Legumbres', precio: 67.5, imagen_url: '00202.jpg')
Producto.create!(id: 204, nombre: 'Malta El Pocillo x 125gr', clasificacion: 'Almacén > Café', precio: 135.0, imagen_url: '00204.jpg')
Producto.create!(id: 210, nombre: 'Margarina Margadan 200gr', clasificacion: 'Lacteos > Mantecas y Margarinas', precio: 50.0, imagen_url: '00210.jpg')
Producto.create!(id: 212, nombre: 'Masa Para Tacos Pandino', clasificacion: 'Frescos y Congelados > Masa para Tacos', precio: 70.0, imagen_url: '00212.jpg')
Producto.create!(id: 213, nombre: 'Mate Cocido Broche De Oro x 25 Uds', clasificacion: 'Almacén > Mate', precio: 59.0, imagen_url: '00213.jpg')
Producto.create!(id: 214, nombre: 'Mate Cocido En Saquitos Cachamate x 25 Uds', clasificacion: 'Almacén > Mate', precio: 56.5, imagen_url: '00214.jpg')
Producto.create!(id: 217, nombre: 'Mayonesa Danica F x 500gr', clasificacion: 'Aderezos > Mayonesas', precio: 95.0, imagen_url: '00217.jpg')
Producto.create!(id: 218, nombre: 'Mayonesa Danica Fiesta 1kg', clasificacion: 'Aderezos > Mayonesas', precio: 174.0, imagen_url: '00218.jpg')
Producto.create!(id: 219, nombre: 'Mayonesa Fanacoa 2755kg', clasificacion: 'Aderezos > Mayonesas', precio: 360.57, imagen_url: '00219.jpg')
Producto.create!(id: 220, nombre: 'Mayonesa Hellmanns 237gr', clasificacion: 'Aderezos > Mayonesas', precio: 65.0, imagen_url: '00220.jpg')
Producto.create!(id: 221, nombre: 'Mayonesa Hellmanns 2755gr', clasificacion: 'Aderezos > Mayonesas', precio: 540.0, imagen_url: '00221.jpg')
Producto.create!(id: 236, nombre: 'Mortadela Goggi Ca?on Feteada x 100gr', clasificacion: 'Fiambreria > Mortadela', precio: 20.0, imagen_url: '00236.jpg')
Producto.create!(id: 237, nombre: 'Mortadela Lario Feteada x 100gr', clasificacion: 'Fiambreria > Mortadela', precio: 50.0, imagen_url: '00237.jpg')
Producto.create!(id: 238, nombre: 'Mortadela Paladini Feteada x 100gr', clasificacion: 'Fiambreria > Mortadela', precio: 58.0, imagen_url: '00238.jpg')
Producto.create!(id: 239, nombre: 'Mostaza Danica 220gr', clasificacion: 'Aderezos > Mostazas', precio: 55.0, imagen_url: '00239.jpg')
Producto.create!(id: 243, nombre: 'Oregano Villa Rica 25gr', clasificacion: 'Condimentos > Condimentos', precio: 38.0, imagen_url: '00243.jpg')
Producto.create!(id: 244, nombre: 'Paleta Fela Feteada x 100gr', clasificacion: 'Fiambreria > Paleta', precio: 44.0, imagen_url: '00244.jpg')
Producto.create!(id: 245, nombre: 'Paleta Figo Feteada x 100gr', clasificacion: 'Fiambreria > Paleta', precio: 12.0, imagen_url: '00245.jpg')
Producto.create!(id: 246, nombre: 'Pan De Hamburguesa Tatito 4 Uds. (albertus)', clasificacion: 'Panadería > Pan de Hamburguesa', precio: 44.5, imagen_url: '00246.jpg')
Producto.create!(id: 248, nombre: 'Pan De Viena Tatito 6 Uds. (albertus)', clasificacion: 'Panadería > Pan de Viena', precio: 44.5, imagen_url: '00248.jpg')
Producto.create!(id: 249, nombre: 'Pan Hamburguesa x 4 Pandino', clasificacion: 'Panadería > Pan de Hamburguesa', precio: 49.99, imagen_url: '00249.jpg')
Producto.create!(id: 250, nombre: 'Pan Lactal Blanco Don Francisco (albertus)', clasificacion: 'Panadería > Lactal', precio: 52.0, imagen_url: '00250.jpg')
Producto.create!(id: 251, nombre: 'Pan Lactal De Salvado Con Semillas 350gr', clasificacion: 'Panadería > Lactal', precio: 124.99, imagen_url: '00251.jpg')
Producto.create!(id: 253, nombre: 'Pan Negro Bollitos Pandino', clasificacion: 'Panadería > Pan Negro', precio: 64.99, imagen_url: '00253.jpg')
Producto.create!(id: 254, nombre: 'Pan Rallado Don Apiro', clasificacion: 'Almacén > Varios', precio: 60.0, imagen_url: '00254.jpg')
Producto.create!(id: 255, nombre: 'Pan Rallado Preferido x 500', clasificacion: 'Almacén > Varios', precio: 85.75, imagen_url: '00255.jpg')
Producto.create!(id: 258, nombre: 'Papas Facu x 500gr', clasificacion: 'Snacks > Papas', precio: 280.0, imagen_url: '00258.jpg')
Producto.create!(id: 259, nombre: 'Papel Higienico Campanita Soft 4un', clasificacion: 'Limpieza > Papel Higiénico', precio: 61.35, imagen_url: '00259.jpg')
Producto.create!(id: 262, nombre: 'Pascualina La Tucumanita 2un', clasificacion: 'Frescos y Congelados > Pascualinas', precio: 69.9, imagen_url: '00262.jpg')
Producto.create!(id: 263, nombre: 'Pascualina Madomi', clasificacion: 'Frescos y Congelados > Pascualinas', precio: 75.7, imagen_url: '00263.jpg')
Producto.create!(id: 264, nombre: 'Pebete x 6 Pandino', clasificacion: 'Panadería > Pebete', precio: 84.99, imagen_url: '00264.jpg')
Producto.create!(id: 265, nombre: 'Pepas Gaona x 180gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 37.0, imagen_url: '00265.jpg')
Producto.create!(id: 266, nombre: 'Picadillo La Negra Carne 90gr', clasificacion: 'Almacén > Enlatados', precio: 30.0, imagen_url: '00266.jpg')
Producto.create!(id: 267, nombre: 'Pimenton Alicante 25gr', clasificacion: 'Condimentos > Condimentos', precio: 41.0, imagen_url: '00267.jpg')
Producto.create!(id: 268, nombre: 'Pimenton Villa Rica 25gr', clasificacion: 'Condimentos > Condimentos', precio: 22.0, imagen_url: '00268.jpg')
Producto.create!(id: 269, nombre: 'Polenta Jose Lopez 500gr', clasificacion: 'Almacén > Legumbres', precio: 35.0, imagen_url: '00269.jpg')
Producto.create!(id: 270, nombre: 'Polenta La Espanola 500gr', clasificacion: 'Almacén > Legumbres', precio: 33.0, imagen_url: '00270.jpg')
Producto.create!(id: 271, nombre: 'Polenta Prestopronta Arcor 500gr', clasificacion: 'Almacén > Polentas', precio: 45.0, imagen_url: '00271.jpg')
Producto.create!(id: 274, nombre: 'Prepizzas Tatito x 3 (albertus)', clasificacion: 'Panadería > Prepizzas', precio: 98.0, imagen_url: '00274.jpg')
Producto.create!(id: 275, nombre: 'Protector Calipso Normal x 20 Sin Desodorante', clasificacion: 'Limpieza > Protección Femenina', precio: 56.0, imagen_url: '00275.jpg')
Producto.create!(id: 276, nombre: 'Provenzal Alicante 25gr', clasificacion: 'Condimentos > Condimentos', precio: 46.0, imagen_url: '00276.jpg')
Producto.create!(id: 277, nombre: 'Provenzal Villa Rica 25gr', clasificacion: 'Condimentos > Condimentos', precio: 38.0, imagen_url: '00277.jpg')
Producto.create!(id: 282, nombre: 'Queso Crema Light La Paulina x 290gr', clasificacion: 'Lacteos > Quesos', precio: 105.1, imagen_url: '00282.jpg')
Producto.create!(id: 286, nombre: 'Queso Cremoso Noal x 100gr', clasificacion: 'Fiambreria > Cremosos', precio: 45.5, imagen_url: '00286.jpg')
Producto.create!(id: 287, nombre: 'Queso Cremoso Santa Maria x 100gr', clasificacion: 'Fiambreria > Cremosos', precio: 43.0, imagen_url: '00287.jpg')
Producto.create!(id: 288, nombre: 'Queso Danbo Noal (tybo) Feteado x 100gr', clasificacion: 'Fiambreria > Dambo', precio: 63.5, imagen_url: '00288.jpg')
Producto.create!(id: 289, nombre: 'Queso Magro Noal x 100gr', clasificacion: 'Fiambreria > Por Salut', precio: 55.0, imagen_url: '00289.jpg')
Producto.create!(id: 291, nombre: 'Queso Por Salut Noal x 100gr', clasificacion: 'Fiambreria > Por Salut', precio: 55.0, imagen_url: '00291.jpg')
Producto.create!(id: 295, nombre: 'Queso Tybo Nulac Feteado x 100gr', clasificacion: 'Fiambreria > Tybo', precio: 50.0, imagen_url: '00295.jpg')
Producto.create!(id: 296, nombre: 'Queso Tybo Santa Maria Feteado x 100gr', clasificacion: 'Fiambreria > Tybo', precio: 58.0, imagen_url: '00296.jpg')
Producto.create!(id: 297, nombre: 'Queso Untable La Paulina x 200gr Vs Sabores', clasificacion: 'Lacteos > Quesos', precio: 94.29, imagen_url: '00297.jpg')
Producto.create!(id: 299, nombre: 'Ravioles Madomi x 500gr', clasificacion: 'Frescos y Congelados > Ravioles', precio: 77.0, imagen_url: '00299.jpg')
Producto.create!(id: 300, nombre: 'Ricota San Lucio x 100gr', clasificacion: 'Fiambreria > Ricota', precio: 15.0, imagen_url: '00300.jpg')
Producto.create!(id: 301, nombre: 'Rollo De Cocina Sol Mayor x 3un', clasificacion: 'Limpieza > Rollos de Cocina', precio: 56.0, imagen_url: '00301.jpg')
Producto.create!(id: 302, nombre: 'Romanito Santa Maria x 100gr', clasificacion: 'Fiambreria > Romanito / Sardo', precio: 85.0, imagen_url: '00302.jpg')
Producto.create!(id: 304, nombre: 'Sal Manto Blanco Fina 500gr', clasificacion: 'Almacén > Sal', precio: 22.8, imagen_url: '00304.jpg')
Producto.create!(id: 305, nombre: 'Sal Manto Blanco Gruesa 500gr', clasificacion: 'Almacén > Sal', precio: 22.8, imagen_url: '00305.jpg')
Producto.create!(id: 306, nombre: 'Salame 66 x 100gr', clasificacion: 'Fiambreria > Salame', precio: 60.0, imagen_url: '00306.jpg')
Producto.create!(id: 308, nombre: 'Salame Don Otto Feteado x 100gr', clasificacion: 'Fiambreria > Salame', precio: 48.0, imagen_url: '00308.jpg')
Producto.create!(id: 310, nombre: 'Salame Goggi Feteado x 100gr', clasificacion: 'Fiambreria > Salame', precio: 48.0, imagen_url: '00310.jpg')
Producto.create!(id: 311, nombre: 'Salchicha 66 6un', clasificacion: 'Frescos y Congelados > Salchichas', precio: 50.0, imagen_url: '00311.jpg')
Producto.create!(id: 312, nombre: 'Salchicha Don Otto 6 Uds', clasificacion: 'Frescos y Congelados > Salchichas', precio: 44.0, imagen_url: '00312.jpg')
Producto.create!(id: 313, nombre: 'Salchicha Paladini 6un', clasificacion: 'Frescos y Congelados > Salchichas', precio: 130.0, imagen_url: '00313.jpg')
Producto.create!(id: 315, nombre: 'Salsa Arcor Para Pizza 340gr', clasificacion: 'Almacén > Salsas', precio: 68.0, imagen_url: '00315.jpg')
Producto.create!(id: 316, nombre: 'Salsa Vanoli Inglesa 180ml', clasificacion: 'Almacén > Salsas', precio: 113.0, imagen_url: '00316.jpg')
Producto.create!(id: 317, nombre: 'Salsa Vanoli Inglesa 950ml', clasificacion: 'Almacén > Salsas', precio: 258.0, imagen_url: '00317.jpg')
Producto.create!(id: 320, nombre: 'Secador Sachi 40', clasificacion: 'Limpieza > Varios', precio: 260.0, imagen_url: '00320.jpg')
Producto.create!(id: 321, nombre: 'Semola Vitina Lucchetti 250gr', clasificacion: 'Almacén > Varios', precio: 89.29, imagen_url: '00321.jpg')
Producto.create!(id: 325, nombre: 'Sorrentinos Madomi x 500gr', clasificacion: 'Frescos y Congelados > Sorrentinos', precio: 100.0, imagen_url: '00325.jpg')
Producto.create!(id: 327, nombre: 'Suavizante Borita x 900ml Todos', clasificacion: 'Limpieza > Suavizante', precio: 98.5, imagen_url: '00327.jpg')
Producto.create!(id: 330, nombre: 'Tapa Para Empanadas Madomi x 12un', clasificacion: 'Frescos y Congelados > Tapas', precio: 55.2, imagen_url: '00330.jpg')
Producto.create!(id: 332, nombre: 'Te La Virginia Rojo 20 Uds', clasificacion: 'Desayuno > Mate', precio: 106.0, imagen_url: '00332.jpg')
Producto.create!(id: 333, nombre: 'Te La Virginia Tilo 25 Uds', clasificacion: 'Desayuno > Mate', precio: 159.5, imagen_url: '00333.jpg')
Producto.create!(id: 335, nombre: 'Te La Virginia x 100 Saq', clasificacion: 'Almacén > Mate', precio: 171.6, imagen_url: '00335.jpg')
Producto.create!(id: 337, nombre: 'Te La Virginia x 50 Saq', clasificacion: 'Almacén > Mate', precio: 92.5, imagen_url: '00337.jpg')
Producto.create!(id: 338, nombre: 'Te Taragui 50un', clasificacion: 'Desayuno > Mate', precio: 91.8, imagen_url: '00338.jpg')
Producto.create!(id: 339, nombre: 'Te Taragui Fil.esp 100s', clasificacion: 'Desayuno > Mate', precio: 187.0, imagen_url: '00339.jpg')
Producto.create!(id: 340, nombre: 'Te Taragui Fil.esp. 25s', clasificacion: 'Desayuno > Mate', precio: 54.0, imagen_url: '00340.jpg')
Producto.create!(id: 341, nombre: 'Te Taragui Tilo 25 Uds', clasificacion: 'Desayuno > Mate', precio: 147.0, imagen_url: '00341.jpg')
Producto.create!(id: 342, nombre: 'Te Villa Rica 25un', clasificacion: 'Desayuno > Mate', precio: 43.0, imagen_url: '00342.jpg')
Producto.create!(id: 343, nombre: 'Toalla Calipso Normal Con Gel Con Alas x 8 Uds', clasificacion: 'Limpieza > Protección Femenina', precio: 42.0, imagen_url: '00343.jpg')
Producto.create!(id: 344, nombre: 'Tomate Perita Arcor 400gr', clasificacion: 'Almacén > Salsas', precio: 78.49, imagen_url: '00344.jpg')
Producto.create!(id: 346, nombre: 'Tostadas Light Gaona 200gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 76.9, imagen_url: '00346.jpg')
Producto.create!(id: 350, nombre: 'Vino Balbo Borges 1,125 Lts', clasificacion: 'Bebidas > Vinos', precio: 112.0, imagen_url: '00350.jpg')
Producto.create!(id: 352, nombre: 'Vino Dada 1 750ml', clasificacion: 'Bebidas > Vinos', precio: 256.0, imagen_url: '00352.jpg')
Producto.create!(id: 353, nombre: 'Vino Don Valentin Lacrado Tinto 750ml', clasificacion: 'Bebidas > Vinos', precio: 195.0, imagen_url: '00353.jpg')
Producto.create!(id: 356, nombre: 'Vino Frizze Evolution 750cc', clasificacion: 'Bebidas > Vinos', precio: 115.0, imagen_url: '00356.jpg')
Producto.create!(id: 361, nombre: 'Vino Termidor Tinto 1lt', clasificacion: 'Bebidas > Vinos', precio: 100.99, imagen_url: '00361.jpg')
Producto.create!(id: 363, nombre: 'Yerba Broche Oro 250gr', clasificacion: 'Almacén > Mate', precio: 83.35, imagen_url: '00363.jpg')
Producto.create!(id: 364, nombre: 'Yerba Broche Oro 500gr', clasificacion: 'Almacén > Mate', precio: 120.0, imagen_url: '00364.jpg')
Producto.create!(id: 365, nombre: 'Yerba Cachamate Con Hierbas 500gr . (amarilla)', clasificacion: 'Almacén > Mate', precio: 143.0, imagen_url: '00365.jpg')
Producto.create!(id: 368, nombre: 'Yerba Cbse 500gr', clasificacion: 'Almacén > Mate', precio: 180.0, imagen_url: '00368.jpg')
Producto.create!(id: 369, nombre: 'Yerba Taragui C/p x 500gr', clasificacion: 'Almacén > Mate', precio: 165.0, imagen_url: '00369.jpg')
Producto.create!(id: 371, nombre: 'Yogur Cerros Tucumanos 1 Lts', clasificacion: 'Lacteos > Yogures', precio: 66.0, imagen_url: '00371.jpg')
Producto.create!(id: 372, nombre: 'Yogur Santa Maria Vasito 125cc', clasificacion: 'Lacteos > Yogures', precio: 26.0, imagen_url: '00372.jpg')
Producto.create!(id: 374, nombre: 'Caldo Knoor Gallina 12 Uds', clasificacion: 'Almacén > Sopas y Caldos', precio: 109.0, imagen_url: '00374.jpg')
Producto.create!(id: 379, nombre: 'Arroz Dos Hermanos lt . Fino x 500gr', clasificacion: 'Almacén > Arroz', precio: 57.0, imagen_url: '00379.jpg')
Producto.create!(id: 381, nombre: 'Arroz Gallo Largo Fino 500gr', clasificacion: 'Almacén > Arroz', precio: 68.0, imagen_url: '00381.jpg')
Producto.create!(id: 384, nombre: 'Crema De Leche Her Bal x 200gr', clasificacion: 'Lacteos > Crema de Leche', precio: 75.0, imagen_url: '00384.jpg')
Producto.create!(id: 386, nombre: 'Crema De Leche Santa Maria 200gr', clasificacion: 'Lacteos > Crema de Leche', precio: 92.0, imagen_url: '00386.jpg')
Producto.create!(id: 387, nombre: 'Desinfectante Lysoform 360 Cm3', clasificacion: 'Limpieza > Varios', precio: 174.0, imagen_url: '00387.jpg')
Producto.create!(id: 405, nombre: 'Leche Descremada En Polvo Purisima x 800gr', clasificacion: 'Lacteos > Leche en Polvo', precio: 434.24, imagen_url: '00405.jpg')
Producto.create!(id: 406, nombre: 'Lustra Muebles Blem 360cc', clasificacion: 'Limpieza > Varios', precio: 197.5, imagen_url: '00406.jpg')
Producto.create!(id: 409, nombre: 'Manteca Tonadita 100gr', clasificacion: 'Lacteos > Mantecas y Margarinas', precio: 52.0, imagen_url: '00409.jpg')
Producto.create!(id: 410, nombre: 'Muzzarella La Rosa x 100gr', clasificacion: 'Fiambreria > Muzzarella', precio: 38.0, imagen_url: '00410.jpg')
Producto.create!(id: 411, nombre: 'Pan Viena x 6 Pandino', clasificacion: 'Panadería > Pan de Viena', precio: 49.99, imagen_url: '00411.jpg')
Producto.create!(id: 413, nombre: 'Papas Facu x 80gr', clasificacion: 'Snacks > Papas', precio: 52.0, imagen_url: '00413.jpg')
Producto.create!(id: 415, nombre: 'Queso Crema Tradicional La Paulina x 290gr', clasificacion: 'Lacteos > Quesos', precio: 125.0, imagen_url: '00415.jpg')
Producto.create!(id: 424, nombre: 'Detergente Magistral x 300cc', clasificacion: 'Limpieza > Detergente', precio: 99.0, imagen_url: '00424.jpg')
Producto.create!(id: 428, nombre: 'Galletas Criollitas De 3 x 100gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 80.0, imagen_url: '00428.jpg')
Producto.create!(id: 429, nombre: 'Yerba Yerbacid C/cascara 500gr', clasificacion: 'Almacén > Mate', precio: 128.0, imagen_url: '00429.jpg')
Producto.create!(id: 430, nombre: 'Queso Cremoso Debaldo x 100gr', clasificacion: 'Fiambreria > Cremosos', precio: 38.0, imagen_url: '00430.jpg')
Producto.create!(id: 432, nombre: 'Galletas Hogarenas Salvado 200gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 63.0, imagen_url: '00432.jpg')
Producto.create!(id: 434, nombre: 'Rollo De Cocina Sussex x 3 Uds', clasificacion: 'Limpieza > Rollos de Cocina', precio: 79.9, imagen_url: '00434.jpg')
Producto.create!(id: 435, nombre: 'Toalla Ladysoft C/a Verde 8un', clasificacion: 'Limpieza > Protección Femenina', precio: 39.0, imagen_url: '00435.jpg')
Producto.create!(id: 439, nombre: 'Fideos Rivoli Moñito 500gr', clasificacion: 'Almacén > Fideos', precio: 74.0, imagen_url: '00439.jpg')
Producto.create!(id: 440, nombre: 'Yogur Yofrey Manfrey Vainilla x 120gr', clasificacion: 'Lacteos > Yogures', precio: 29.0, imagen_url: '00440.jpg')
Producto.create!(id: 446, nombre: 'Nuez Moscada Alicante x 25gr', clasificacion: 'Condimentos > Condimentos', precio: 125.0, imagen_url: '00446.jpg')
Producto.create!(id: 447, nombre: 'Salsa Golf Danica 220ml', clasificacion: 'Aderezos > Salsa Golf', precio: 53.0, imagen_url: '00447.jpg')
Producto.create!(id: 449, nombre: 'Yogur Yofrey Manfrey Frutilla 120gr', clasificacion: 'Lacteos > Yogures', precio: 29.0, imagen_url: '00449.jpg')
Producto.create!(id: 451, nombre: 'Galletas Chocolinas 170gr . Bagley', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 77.5, imagen_url: '00451.jpg')
Producto.create!(id: 455, nombre: 'Maiz Pisingallo Verizzia', clasificacion: 'Almacén > Legumbres', precio: 32.0, imagen_url: '00455.jpg')
Producto.create!(id: 456, nombre: 'Por Salut Santa Maria x 100gr', clasificacion: 'Fiambreria > Cremosos', precio: 48.0, imagen_url: '00456.jpg')
Producto.create!(id: 458, nombre: 'Rebozador Preferido 500gr', clasificacion: 'Almacén > Rebozadores', precio: 88.5, imagen_url: '00458.jpg')
Producto.create!(id: 460, nombre: 'Lasagna Matarazzo 250gr', clasificacion: 'Almacén > Varios', precio: 105.0, imagen_url: '00460.jpg')
Producto.create!(id: 464, nombre: 'Picadillo Changuito Carne 90gr', clasificacion: 'Almacén > Enlatados', precio: 30.0, imagen_url: '00464.jpg')
Producto.create!(id: 466, nombre: 'Yerba Nobleza Gaucha 500gr', clasificacion: 'Almacén > Mate', precio: 165.9, imagen_url: '00466.jpg')
Producto.create!(id: 467, nombre: 'Aceite Natura Girasol x 900ml', clasificacion: 'Almacén > Aceites', precio: 205.0, imagen_url: '00467.jpg')
Producto.create!(id: 470, nombre: 'Bizcochuelo Godet Marmolado 480gr', clasificacion: 'Almacén > Postres', precio: 108.0, imagen_url: '00470.jpg')
Producto.create!(id: 472, nombre: 'Condimento Para Pizza Villa Rica 25gr', clasificacion: 'Condimentos > Condimentos', precio: 25.0, imagen_url: '00472.jpg')
Producto.create!(id: 474, nombre: 'Dentifrico Kolynos 70gr', clasificacion: 'Limpieza > Dentifrico', precio: 98.0, imagen_url: '00474.jpg')
Producto.create!(id: 480, nombre: 'Leche Entera En Polvo Purisima x 800gr', clasificacion: 'Lacteos > Leche en Polvo', precio: 434.24, imagen_url: '00480.jpg')
Producto.create!(id: 481, nombre: 'Mayonesa Hellmanns 118gr', clasificacion: 'Aderezos > Mayonesas', precio: 30.0, imagen_url: '00481.jpg')
Producto.create!(id: 482, nombre: 'Mostaza Savora 1kg', clasificacion: 'Aderezos > Mostazas', precio: 219.99, imagen_url: '00482.jpg')
Producto.create!(id: 483, nombre: 'Pimienta Blanca Alicante 25gr', clasificacion: 'Condimentos > Condimentos', precio: 66.9, imagen_url: '00483.jpg')
Producto.create!(id: 487, nombre: 'Velas Malambo x 4un', clasificacion: 'Limpieza > Velas', precio: 26.0, imagen_url: '00487.jpg')
Producto.create!(id: 489, nombre: 'Aceite Despensero x 900ml', clasificacion: 'Almacén > Aceites', precio: 175.5, imagen_url: '00489.jpg')
Producto.create!(id: 490, nombre: 'Alcohol San Iginio 250cc', clasificacion: 'Limpieza > Alcohol', precio: 69.0, imagen_url: '00490.jpg')
Producto.create!(id: 492, nombre: 'Azucar Hileret Light x 500gr paq', clasificacion: 'Desayuno > Edulcorantes', precio: 77.0, imagen_url: '00492.jpg')
Producto.create!(id: 494, nombre: 'Cerveza Schneider Rubia Lata 473ml', clasificacion: 'Bebidas > Cervezas y Fernet', precio: 67.5, imagen_url: '00494.jpg')
Producto.create!(id: 498, nombre: 'Durazno En Lata Df x 820gr', clasificacion: 'Almacén > Enlatados', precio: 139.5, imagen_url: '00498.jpg')
Producto.create!(id: 499, nombre: 'Fideos Verizzia Spaguetti', clasificacion: 'Almacén > Fideos', precio: 39.0, imagen_url: '00499.jpg')
Producto.create!(id: 501, nombre: 'Hamburguesa Riccisimas 2 x 65gr', clasificacion: 'Frescos y Congelados > Hamburguesas', precio: 39.0, imagen_url: '00501.jpg')
Producto.create!(id: 503, nombre: 'Harina Reina Ana 0000 x 1kg', clasificacion: 'Almacén > Harinas', precio: 62.5, imagen_url: '00503.jpg')
Producto.create!(id: 505, nombre: 'Jugo Baggio Fresh Mix Frutal 1,1lt', clasificacion: 'Bebidas > Jugos', precio: 62.0, imagen_url: '00505.jpg')
Producto.create!(id: 506, nombre: 'Jugo Baggio Fresh Naranja Dulce 1,1lt', clasificacion: 'Bebidas > Jugos', precio: 62.0, imagen_url: '00506.jpg')
Producto.create!(id: 507, nombre: 'Ketchup Danica 50', clasificacion: 'Aderezos > Ketchup', precio: 19.65, imagen_url: '00507.jpg')
Producto.create!(id: 508, nombre: 'Leche La Serenisima Sachet Descremada 1lt', clasificacion: 'Lacteos > Leche', precio: 86.0, imagen_url: '00508.jpg')
Producto.create!(id: 509, nombre: 'Leche La Serenisima Sachet Entero 1lt', clasificacion: 'Lacteos > Leche', precio: 86.0, imagen_url: '00509.jpg')
Producto.create!(id: 510, nombre: 'Lenteja La Espanola x 400gr', clasificacion: 'Almacén > Legumbres', precio: 96.0, imagen_url: '00510.jpg')
Producto.create!(id: 511, nombre: 'Mate Cocido Amanda x 25 Uds', clasificacion: 'Almacén > Mate', precio: 58.5, imagen_url: '00511.jpg')
Producto.create!(id: 512, nombre: 'Mayonesa Mayodan 3kg', clasificacion: 'Aderezos > Mayonesas', precio: 275.0, imagen_url: '00512.jpg')
Producto.create!(id: 513, nombre: 'Mostaza Danica 60gr', clasificacion: 'Aderezos > Mostazas', precio: 17.0, imagen_url: '00513.jpg')
Producto.create!(id: 514, nombre: 'Mostaza Savora Original x 250gr', clasificacion: 'Aderezos > Mostazas', precio: 81.0, imagen_url: '00514.jpg')
Producto.create!(id: 515, nombre: 'Poroto Aluvia La Espanola 500gr', clasificacion: 'Almacén > Legumbres', precio: 102.0, imagen_url: '00515.jpg')
Producto.create!(id: 516, nombre: 'Pure De Papas Knorr x 125gr', clasificacion: 'Almacén > Varios', precio: 97.5, imagen_url: '00516.jpg')
Producto.create!(id: 517, nombre: 'Pure De Tomate Sabores Del Valle 520gr', clasificacion: 'Almacén > Salsas', precio: 55.0, imagen_url: '00517.jpg')
Producto.create!(id: 518, nombre: 'Salame Bierzo Feteado x 100gr', clasificacion: 'Fiambreria > Salame', precio: 78.0, imagen_url: '00518.jpg')
Producto.create!(id: 522, nombre: 'Tomate Triturado Sabores Del Valle 1kg', clasificacion: 'Almacén > Salsas', precio: 112.0, imagen_url: '00522.jpg')
Producto.create!(id: 524, nombre: 'Yerba Amanda 250gr', clasificacion: 'Almacén > Mate', precio: 88.0, imagen_url: '00524.jpg')
Producto.create!(id: 525, nombre: 'Yerba Amanda 500gr', clasificacion: 'Almacén > Mate', precio: 170.0, imagen_url: '00525.jpg')
Producto.create!(id: 526, nombre: 'Yerba Taragui 250gr', clasificacion: 'Almacén > Mate', precio: 90.0, imagen_url: '00526.jpg')
Producto.create!(id: 529, nombre: 'Aceite De Girasol Clarisimo 900ml', clasificacion: 'Almacén > Aceites', precio: 208.0, imagen_url: '00529.jpg')
Producto.create!(id: 530, nombre: 'Aceitunas Negras Blati 500gr', clasificacion: 'Fiambreria > Aceitunas', precio: 265.0, imagen_url: '00530.jpg')
Producto.create!(id: 533, nombre: 'Aceitunas Verdes Sueltas x 100gr', clasificacion: 'Fiambreria > Aceitunas', precio: 20.0, imagen_url: '00533.jpg')
Producto.create!(id: 541, nombre: 'Azucar Light Lheritier 350gr', clasificacion: 'Desayuno > Edulcorantes', precio: 72.0, imagen_url: '00541.jpg')
Producto.create!(id: 542, nombre: 'Budin Dale Con Frutas Tia Maruca x 170gr', clasificacion: 'Almacén > Varios', precio: 35.0, imagen_url: '00542.jpg')
Producto.create!(id: 543, nombre: 'Cafe La Virginia Instantaneo 50gr . Clasico', clasificacion: 'Almacén > Café', precio: 126.85, imagen_url: '00543.jpg')
Producto.create!(id: 544, nombre: 'Cafe La Virginia Instantaneo Suave 50gr', clasificacion: 'Almacén > Café', precio: 126.85, imagen_url: '00544.jpg')
Producto.create!(id: 549, nombre: 'Cerveza Isenbeck Lata 473ml', clasificacion: 'Bebidas > Cervezas y Fernet', precio: 65.0, imagen_url: '00549.jpg')
Producto.create!(id: 551, nombre: 'Cif Vidrios Celeste 450ml', clasificacion: 'Limpieza > Varios', precio: 79.0, imagen_url: '00551.jpg')
Producto.create!(id: 554, nombre: 'Detergente Bora 135ml', clasificacion: 'Limpieza > Detergente', precio: 33.0, imagen_url: '00554.jpg')
Producto.create!(id: 558, nombre: 'Edulcorante Barny 250ml', clasificacion: 'Desayuno > Edulcorantes', precio: 76.5, imagen_url: '00558.jpg')
Producto.create!(id: 562, nombre: 'Fideos Chicago Spaguetti 500gr', clasificacion: 'Almacén > Fideos', precio: 48.0, imagen_url: '00562.jpg')
Producto.create!(id: 563, nombre: 'Fideos Frescos La Tucumanita 500gr', clasificacion: 'Almacén > Fideos', precio: 76.8, imagen_url: '00563.jpg')
Producto.create!(id: 564, nombre: 'Fideos La Providencia Moño x 500gr', clasificacion: 'Almacén > Fideos', precio: 55.0, imagen_url: '00564.jpg')
Producto.create!(id: 569, nombre: 'Gancia Americano x 950ml', clasificacion: 'Bebidas > Aperitivos', precio: 270.0, imagen_url: '00569.jpg')
Producto.create!(id: 571, nombre: 'Hamburguesa Paty Finita 2un', clasificacion: 'Frescos y Congelados > Hamburguesas', precio: 77.5, imagen_url: '00571.jpg')
Producto.create!(id: 573, nombre: 'Harina Leudante Corona De Trigo 1kg', clasificacion: 'Almacén > Harinas', precio: 71.0, imagen_url: '00573.jpg')
Producto.create!(id: 580, nombre: 'Jabon Lux 125gr', clasificacion: 'Limpieza > Shampoo', precio: 52.5, imagen_url: '00580.jpg')
Producto.create!(id: 581, nombre: 'Jabon Rexona 125gr', clasificacion: 'Limpieza > Shampoo', precio: 43.5, imagen_url: '00581.jpg')
Producto.create!(id: 583, nombre: 'Jugo Baggio Durazno 1lt', clasificacion: 'Bebidas > Jugos', precio: 103.0, imagen_url: '00583.jpg')
Producto.create!(id: 585, nombre: 'Jugo Baggio Multi Fruta 200cc', clasificacion: 'Bebidas > Jugos', precio: 24.0, imagen_url: '00585.jpg')
Producto.create!(id: 588, nombre: 'Leche En Polvo Entera Lheritier 350gr', clasificacion: 'Lacteos > Leche en Polvo', precio: 205.0, imagen_url: '00588.jpg')
Producto.create!(id: 591, nombre: 'Lentejas Arcor 320gr', clasificacion: 'Almacén > Enlatados', precio: 97.9, imagen_url: '00591.jpg')
Producto.create!(id: 595, nombre: 'Mate Cocido Taragui En Saquitos x 100 Uds', clasificacion: 'Almacén > Mate', precio: 207.0, imagen_url: '00595.jpg')
Producto.create!(id: 599, nombre: 'Mayonesa Danica F 100gr', clasificacion: 'Aderezos > Mayonesas', precio: 20.0, imagen_url: '00599.jpg')
Producto.create!(id: 600, nombre: 'Mayonesa Danica F. 220gr', clasificacion: 'Aderezos > Mayonesas', precio: 45.0, imagen_url: '00600.jpg')
Producto.create!(id: 601, nombre: 'Mayonesa Natura 125gr', clasificacion: 'Aderezos > Mayonesas', precio: 32.0, imagen_url: '00601.jpg')
Producto.create!(id: 603, nombre: 'Obleas Tym x 46gr', clasificacion: 'Almacén > Gall. Dulces y Saladas', precio: 16.0, imagen_url: '00603.jpg')
Producto.create!(id: 606, nombre: 'Papel Higienico Eco Family 6 x 30 M', clasificacion: 'Limpieza > Papel Higiénico', precio: 90.0, imagen_url: '00606.jpg')
Producto.create!(id: 607, nombre: 'Papel Higienico Higienol Export 4 x 30 Mts', clasificacion: 'Limpieza > Papel Higiénico', precio: 72.0, imagen_url: '00607.jpg')
Producto.create!(id: 613, nombre: 'Rejilla Marilu Bar', clasificacion: 'Limpieza > Rejilla', precio: 26.75, imagen_url: '00613.jpg')
Producto.create!(id: 616, nombre: 'Salsa Golf Benidorm 500ml', clasificacion: 'Aderezos > Salsa Golf', precio: 155.0, imagen_url: '00616.jpg')
Producto.create!(id: 619, nombre: 'Stevia Hileret x 200 bot', clasificacion: 'Almacén > Edulcorantes', precio: 170.0, imagen_url: '00619.jpg')
Producto.create!(id: 620, nombre: 'Suavizante Vivere Clasico 900ml', clasificacion: 'Limpieza > Suavizante', precio: 135.0, imagen_url: '00620.jpg')
Producto.create!(id: 621, nombre: 'Tapa Para Empanadas La Tucumanita 12un', clasificacion: 'Frescos y Congelados > Tapas', precio: 52.0, imagen_url: '00621.jpg')
Producto.create!(id: 622, nombre: 'Tomate Triturado La Riojanita 980gr', clasificacion: 'Almacén > Salsas', precio: 115.5, imagen_url: '00622.jpg')
Producto.create!(id: 623, nombre: 'Tomate Triturado La Riojanita Doy Pack 500gr', clasificacion: 'Almacén > Salsas', precio: 62.75, imagen_url: '00623.jpg')
Producto.create!(id: 624, nombre: 'Trigo Jose Lopez 500gr', clasificacion: 'Almacén > Legumbres', precio: 71.0, imagen_url: '00624.jpg')
Producto.create!(id: 625, nombre: 'Trigo La Espanola 500gr', clasificacion: 'Almacén > Legumbres', precio: 65.0, imagen_url: '00625.jpg')
Producto.create!(id: 628, nombre: 'Vino Finca La Sofia Malbec x 750 Mm', clasificacion: 'Bebidas > Vinos', precio: 128.0, imagen_url: '00628.jpg')
Producto.create!(id: 646, nombre: 'Sardo Debaldo x 100gr', clasificacion: 'Fiambreria > Sardo', precio: 60.0, imagen_url: '00646.jpg')
Producto.create!(id: 653, nombre: 'Cappuccino La Virginia Light 100gr', clasificacion: 'Almacén > Café', precio: 149.0, imagen_url: '00653.jpg')
Producto.create!(id: 655, nombre: 'Detergente Borita Ropa Fina 150ml', clasificacion: 'Limpieza > Detergente', precio: 36.0, imagen_url: '00655.jpg')
Producto.create!(id: 656, nombre: 'Detergente Magistral x 215ml', clasificacion: 'Limpieza > Detergente', precio: 73.0, imagen_url: '00656.jpg')
Producto.create!(id: 657, nombre: 'Espiral x 5 Caja x 12 Uds', clasificacion: 'Limpieza > Espiral', precio: 85.0, imagen_url: '00657.jpg')
Producto.create!(id: 658, nombre: 'Franela Marilu 40*48', clasificacion: 'Limpieza > Rejilla', precio: 78.0, imagen_url: '00658.jpg')
Producto.create!(id: 659, nombre: 'Galletas Coquitas Bagley 170gr', clasificacion: 'Almacén > Varios', precio: 69.5, imagen_url: '00659.jpg')
Producto.create!(id: 660, nombre: 'Galletas De Arroz Con Sal Risky Dit x 100gr', clasificacion: 'Almacén > Varios', precio: 60.0, imagen_url: '00660.jpg')
Producto.create!(id: 671, nombre: 'Jabon En Pan Argentino x 2uds', clasificacion: 'Limpieza > Varios', precio: 59.0, imagen_url: '00671.jpg')
Producto.create!(id: 673, nombre: 'Jabon Zorro Plus A Mano 3kg', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 365.0, imagen_url: '00673.jpg')
Producto.create!(id: 675, nombre: 'Jabon Zorro Plus Matic 800gr', clasificacion: 'Limpieza > Limpiador de Ropa', precio: 100.0, imagen_url: '00675.jpg')
Producto.create!(id: 677, nombre: 'Lavavajillas Ala 750ml . (detergente)', clasificacion: 'Limpieza > Lavavajillas', precio: 83.7, imagen_url: '00677.jpg')
Producto.create!(id: 680, nombre: 'Lustra Mueble Ceramicol 360cc', clasificacion: 'Limpieza > Varios', precio: 165.0, imagen_url: '00680.jpg')
Producto.create!(id: 687, nombre: 'Pascualina La Tucuma Light', clasificacion: 'Frescos y Congelados > Pascualinas', precio: 75.0, imagen_url: '00687.jpg')
Producto.create!(id: 690, nombre: 'Queso Azul Manfrey 180gr', clasificacion: 'Lacteos > Quesos', precio: 107.5, imagen_url: '00690.jpg')
Producto.create!(id: 691, nombre: 'Queso Finlandia Clasico 200gr', clasificacion: 'Lacteos > Quesos', precio: 102.0, imagen_url: '00691.jpg')
Producto.create!(id: 692, nombre: 'Raid Mata Moscas y Mosquitos 360 Cm', clasificacion: 'Limpieza > Varios', precio: 250.0, imagen_url: '00692.jpg')
Producto.create!(id: 697, nombre: 'Aceite De Girasol Clarisimo 3lt', clasificacion: 'Almacén > Aceites', precio: 635.0, imagen_url: '00697.jpg')
Producto.create!(id: 700, nombre: 'Cacao Nesquik 180gr', clasificacion: 'Desayuno > Cacao', precio: 93.99, imagen_url: '00700.jpg')
Producto.create!(id: 703, nombre: 'Edulcorante El Pocillo 180ml', clasificacion: 'Desayuno > Edulcorantes', precio: 68.5, imagen_url: '00703.jpg')
Producto.create!(id: 704, nombre: 'Fecula Glutal x 500gr', clasificacion: 'Almacén > Varios', precio: 100.0, imagen_url: '00704.jpg')
Producto.create!(id: 705, nombre: 'Gaseosa Pepsi 3lt', clasificacion: 'Bebidas > Gaseosas', precio: 155.0, imagen_url: '00705.jpg')
Producto.create!(id: 709, nombre: 'Mermelada Emeth Ciruela Light x 500gr', clasificacion: 'Desayuno > Mermeladas', precio: 70.0, imagen_url: '00709.jpg')
Producto.create!(id: 711, nombre: 'Mermelada Emeth Durazno Light x 500gr', clasificacion: 'Desayuno > Mermeladas', precio: 70.0, imagen_url: '00711.jpg')
Producto.create!(id: 718, nombre: 'Avena La Espanola 500gr', clasificacion: 'Almacén > Legumbres', precio: 72.0, imagen_url: '00718.jpg')
Producto.create!(id: 722, nombre: 'Crema De Leche La Serenisima 200ml', clasificacion: 'Lacteos > Crema de Leche', precio: 84.8, imagen_url: '00722.jpg')
Producto.create!(id: 724, nombre: 'Gelatina Godet Todas x 100', clasificacion: 'Almacén > Postres', precio: 53.0, imagen_url: '00724.jpg')
Producto.create!(id: 729, nombre: 'Papel Higienico Campanita Clasic 4 x 50m', clasificacion: 'Limpieza > Papel Higiénico', precio: 78.0, imagen_url: '00729.jpg')
Producto.create!(id: 732, nombre: 'Dulce De Leche Santa Maria 1kg', clasificacion: 'Lacteos > Dulce de Leche', precio: 250.0, imagen_url: '00732.jpg')
Producto.create!(id: 733, nombre: 'Galletas Azucaradas Arcor 80gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 23.5, imagen_url: '00733.jpg')
Producto.create!(id: 734, nombre: 'Galletas Fauna Mauri 150gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 37.0, imagen_url: '00734.jpg')
Producto.create!(id: 736, nombre: 'Gaseosa Pepsi 2lt', clasificacion: 'Bebidas > Gaseosas', precio: 129.0, imagen_url: '00736.jpg')
Producto.create!(id: 737, nombre: 'Jamon Cocido Paladini Feteado x 100gr', clasificacion: 'Fiambreria > Jamón', precio: 80.0, imagen_url: '00737.jpg')
Producto.create!(id: 738, nombre: 'Jamon Cocido Paladini x Pieza ( 6kg .)', clasificacion: 'Fiambreria > Jamón', precio: 3.96, imagen_url: '00738.jpg')
Producto.create!(id: 740, nombre: 'Queso Rallado La Serenisima 40gr', clasificacion: 'Lacteos > Quesos', precio: 72.0, imagen_url: '00740.jpg')
Producto.create!(id: 741, nombre: 'Salsa Para Pizza Vanoli 340gr', clasificacion: 'Almacén > Salsas', precio: 65.5, imagen_url: '00741.jpg')
Producto.create!(id: 742, nombre: 'Dentifrico Colgate Herbal 70gr', clasificacion: 'Limpieza > Dentifrico', precio: 114.0, imagen_url: '00742.jpg')
Producto.create!(id: 743, nombre: 'Dentifrico Odolito Niños 50gr', clasificacion: 'Limpieza > Dentifrico', precio: 59.4, imagen_url: '00743.jpg')
Producto.create!(id: 746, nombre: 'Pepas Gaona x 315gr', clasificacion: 'Desayuno > Gall Dulces y Saladas', precio: 52.0, imagen_url: '00746.jpg')
Producto.create!(id: 747, nombre: 'Te Negro Green Hills Classic x 25 Uds', clasificacion: 'Almacén > Otros', precio: 63.0, imagen_url: '00747.jpg')
Producto.create!(id: 751, nombre: 'Budin Con Frutas Bimbo 200gr', clasificacion: 'Almacén > Varios', precio: 115.0, imagen_url: '00751.jpg')
Producto.create!(id: 755, nombre: 'Duraznos Light Cumana x 800gr', clasificacion: 'Almacén > Enlatados', precio: 149.97, imagen_url: '00755.jpg')
Producto.create!(id: 756, nombre: 'Guantes Pequenos Make', clasificacion: 'Limpieza > Varios', precio: 137.0, imagen_url: '00756.jpg')
Producto.create!(id: 760, nombre: 'Mayonesa Bc 125gr', clasificacion: 'Aderezos > Mayonesas', precio: 35.5, imagen_url: '00760.jpg')
Producto.create!(id: 766, nombre: 'Queso Finlandia Light 200gr', clasificacion: 'Lacteos > Quesos', precio: 102.0, imagen_url: '00766.jpg')
Producto.create!(id: 767, nombre: 'Rebozador Sol De Campo x 400gr', clasificacion: 'Almacén > Rebozadores', precio: 60.0, imagen_url: '00767.jpg')
Producto.create!(id: 769, nombre: 'Vinagre De Alcohol El Parrillero 1lt', clasificacion: 'Almacén > Vinagres', precio: 47.49, imagen_url: '00769.jpg')
Producto.create!(id: 773, nombre: 'Queso Cremoso Mi Campo x 100gr', clasificacion: 'Fiambreria > Cremosos', precio: 38.0, imagen_url: '00773.jpg')
Producto.create!(id: 775, nombre: 'Grasa Faty 500gr', clasificacion: 'Almacén > Varios', precio: 92.0, imagen_url: '00775.jpg')
Producto.create!(id: 776, nombre: 'Pan Dulce Buon Natale Con Frutas 400gr', clasificacion: 'Almacén > Varios', precio: 115.0, imagen_url: '00776.jpg')
Producto.create!(id: 777, nombre: 'Salchichon Primavera Lario x 100gr', clasificacion: 'Fiambreria > Salchichon', precio: 40.0, imagen_url: '00777.jpg')
Producto.create!(id: 785, nombre: 'Yerba Verdeflor x 500gr . Varios Sabres', clasificacion: 'Almacén > Mate', precio: 150.0, imagen_url: '00785.jpg')
Producto.create!(id: 789, nombre: 'Aceitunas Riojanita x 130gr', clasificacion: 'Fiambreria > Aceitunas', precio: 59.5, imagen_url: '00789.jpg')
Producto.create!(id: 791, nombre: 'Dr. Lemon Con Vodka Pomelo 1lt', clasificacion: 'Bebidas > Aperitivos', precio: 149.0, imagen_url: '00791.jpg')
Producto.create!(id: 793, nombre: 'Jamon Cocido Lario x Pieza', clasificacion: 'Fiambreria > Jamón', precio: 3.726, imagen_url: '00793.jpg')
Producto.create!(id: 795, nombre: 'Mostaza Savora 3kg', clasificacion: 'Aderezos > Mostazas', precio: 438.0, imagen_url: '00795.jpg')
Producto.create!(id: 797, nombre: 'Queso Untable Jamon Manfrey 180gr', clasificacion: 'Lacteos > Quesos', precio: 107.5, imagen_url: '00797.jpg')
Producto.create!(id: 798, nombre: 'Queso Untable Manfrey Gruyere 180gr', clasificacion: 'Lacteos > Quesos', precio: 107.5, imagen_url: '00798.jpg')
Producto.create!(id: 802, nombre: 'Algodon Estrella 75gr', clasificacion: 'Limpieza > Varios', precio: 58.0, imagen_url: '00802.jpg')
Producto.create!(id: 804, nombre: 'Esponja De Fibra Make Rosa', clasificacion: 'Limpieza > Virulana', precio: 70.0, imagen_url: '00804.jpg')
Producto.create!(id: 809, nombre: 'Pan De Miga Delizioso (blanco Sin Corteza)', clasificacion: 'Panadería > Miga', precio: 170.0, imagen_url: '00809.jpg')
Producto.create!(id: 810, nombre: 'Pure De Tomate Arcor 520gr', clasificacion: 'Almacén > Salsas', precio: 64.0, imagen_url: '00810.jpg')
Producto.create!(id: 813, nombre: 'Salsa Filetto Sabores Del Valle 340gr', clasificacion: 'Almacén > Salsas', precio: 64.0, imagen_url: '00813.jpg')
Producto.create!(id: 814, nombre: 'Salsa Pizza Sabores Del Valle 340gr', clasificacion: 'Almacén > Salsas', precio: 64.0, imagen_url: '00814.jpg')
Producto.create!(id: 815, nombre: 'Salsa Sabores Del Valle Pomarola 340gr', clasificacion: 'Almacén > Salsas', precio: 64.0, imagen_url: '00815.jpg')
Producto.create!(id: 819, nombre: 'Esponja Make Espunela Antiadherente', clasificacion: 'Limpieza > Varios', precio: 86.9, imagen_url: '00819.jpg')
Producto.create!(id: 825, nombre: 'Desodorante Glade 360cc', clasificacion: 'Limpieza > Varios', precio: 99.5, imagen_url: '00825.jpg')